apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigassdigitalcalendar-website
spec:
  selector:
    matchLabels:
      app: bigassdigitalcalendar-website
  replicas: 1
  template:
    metadata:
      labels:
        app: bigassdigitalcalendar-website
    spec:
      containers:
      - name: bigassdigitalcalendar-website
        image: local/bigassdigitalcalendar-website:1.0.0
        imagePullPolicy: Never
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bigassdigitalcalendar-web-service
spec:
  selector:
    app: bigassdigitalcalendar-website
  ports:
    - protocol: TCP
      port: 8080
